#!/bin/bash

#A simple guessing game

#Get a random number < 100
target=$(($RANDOM % 100))

#Intitialize the users's guess
guesss=

until [[ $guess -eq $target ]]; do
        read -p "Take a guess: " guess
        if [[ $guess -lt $target ]]; then
                echo "Higher!"
        elif [[ $guess -gt $target ]]; then
                echo "Lower!"
        else
                echo "You found it!"
        fi
done

exit 0

