#!/bin/bash

#Simple note-taking script
#Author: reindert
#get the date
date=$(date)
#get the topic
topic=$1
#filename to write to
filename=~/test/${topic}notes.txt
#get the topic
topic=$1
#Ask user for input
read -p "Your note: " note

if [[ $note ]]'; then
  echo $(date): $note >> "$filename"
  ecto "Note \'$note\' saved to $filename"
else
  echo "No input; note wasn't saved."
fi
